LOAD DATA
INFILE 'BILLING_FORMAT_01_ACCESS_SYSTEM.csv' 
BADFILE 'BILLING_FORMAT_01_ACCESS_SYSTEM.bad'

INTO TABLE EDMACCESS.BILL_EXTRACTION
INSERT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'TRAILING NULLCOLS
(
MISEENSERVICE                                         DATE "yyyy-mm-dd",


)